### ISSUE TITLE
Make app available on Play Store again

### ISSUE THREAD

**Issue by rumwerfer** [Trustroots/trustroots-expo-mobile#14]
Somebody wrote us that the app can't be found in the play store: https://play.google.com/store/apps/details?id=org.trustroots.trustrootsApp

Do we know why it was removed?

**Comment by rumwerfer** [comment]
Any news on that? People asking: https://trustroots.zendesk.com/inbox/conversations/2811

**Comment by simison** [comment]
Yep so this needs little more work to get working. We basically need to update the app to the latest Expo.io SDK and re-submit.

**Comment by simison** [comment]
Updated (https://github.com/Trustroots/trustroots-expo-mobile/pull/15) and it's now available again 👍 

Thanks for the patience.
