### ISSUE TITLE
Keyboard covers text composition field

### ISSUE THREAD

**Issue by noahsmindfuck** [Trustroots/trustroots-expo-mobile#18]
Report froma user via [Zendesk](https://trustroots.zendesk.com/agent/tickets/2870):

The biggest issue I've found so far is with the mobile app: while 
composing a message the bar in which I'm writing doesn't shift up when
the keyboard appears, hence it is covered by it while I'm composing, 
therefore I can't see and quickly correct typos and so on. It would make
the platform much more usable a correction on this feature.

**Comment by ahstro** [comment]
For navigability: this has also been reported here: Trustroots/trustroots#1101

I tried looking into this, and the issue seemed largely gone when I got the app running in Expo on my phone. Maybe there was a problem with Expo itself, so that a new build would fix this? I'll explore a bit more today.

**Comment by simison** [comment]
It might depend on browser/Android version, since I believe Expo will just use the OS default browser to render the webview.

**Comment by dustinmichels** [comment]
This has been a pretty major issue on my android phone and an issue for most TrustRoots users I have met. I have met several people that use the website instead of the app for this reason alone. I am interested in helping to fix it!

**Comment by simison** [comment]
@dustinmichels that would be fantastic! Are you in our volunteer chat? Let us know if you'd need any help.

**Comment by dustinmichels** [comment]
I am not. How can I join?

**Comment by simison** [comment]
@dustinmichels I sent you an invite to your Github email.

**Comment by platschi** [comment]
+1 indeed big issue, find it very annoying myself and heard the same thing from other Trustroots visitors recently. 

I'm happy to help testing any updated app versions.

**Comment by simison** [comment]
Should've gotten fixed by https://github.com/Trustroots/trustroots-expo-mobile/pull/29

We had another report but it could be web browser or outdated web app.
